# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

* R.: Sim, pode receber.

In [2]:
matriz = [
    [[1,2], [3,4]],
    [[5,6], [7,8]]
]

matriz

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [3]:
genes_imuno = ["interleucina_6", "interferon_gama", "TNF-alpha", "interleucina_12", "TGF-beta"]
interleucina_6_lista = [
    len(genes_imuno[0]),
    genes_imuno[0][:2],
    genes_imuno[0].count("a"),
    "hu" in genes_imuno[0]
]
interferon_gama_lista = [
    len(genes_imuno[1]),
    genes_imuno[1][:2],
    genes_imuno[1].count("a"),
    "hu" in genes_imuno[1]
]
TNF_alpha_lista = [
    len(genes_imuno[2]),
    genes_imuno[2][:2],
    genes_imuno[2].count("a"),
    "hu" in genes_imuno[2]
]
interleucina_12_lista = [
    len(genes_imuno[3]),
    genes_imuno[3][:2],
    genes_imuno[3].count("a"),
    "hu" in genes_imuno[3]
]
TGF_beta_lista = [
    len(genes_imuno[4]),
    genes_imuno[4][:2],
    genes_imuno[4].count("a"),
    "hu" in genes_imuno[4]
]

In [4]:
obj_multi = [interleucina_6_lista,
             interferon_gama_lista,
             TNF_alpha_lista,
             interleucina_12_lista,
             TGF_beta_lista]
obj_multi

[[14, 'in', 1, False],
 [15, 'in', 2, False],
 [9, 'TN', 2, False],
 [15, 'in', 1, False],
 [8, 'TG', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [5]:
import numpy as np

In [6]:
array_ex03 = np.array(obj_multi)

array_ex03

array([['14', 'in', '1', 'False'],
       ['15', 'in', '2', 'False'],
       ['9', 'TN', '2', 'False'],
       ['15', 'in', '1', 'False'],
       ['8', 'TG', '1', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [7]:
array_ex03[2, :]

array(['9', 'TN', '2', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [8]:
'hu' in array_ex03

False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [9]:
#Segundo gene
array_ex03[[1],[1,2]]

array(['in', '2'], dtype='<U21')

In [10]:
#Quarto gene
array_ex03[[3],[1,2]]

array(['in', '1'], dtype='<U21')

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [11]:
dict_ex10 = {
    genes_imuno[0]: interleucina_6_lista,
    genes_imuno[1]: interferon_gama_lista,
    genes_imuno[2]: TNF_alpha_lista,
    genes_imuno[3]: interleucina_12_lista,
    genes_imuno[4]: TGF_beta_lista
}
dict_ex10

{'interleucina_6': [14, 'in', 1, False],
 'interferon_gama': [15, 'in', 2, False],
 'TNF-alpha': [9, 'TN', 2, False],
 'interleucina_12': [15, 'in', 1, False],
 'TGF-beta': [8, 'TG', 1, False]}

In [12]:
import pandas as pd

In [13]:
df_ex7 = pd.DataFrame(dict_ex10).T

df_exerc7 = df_ex7.rename(columns={0:"numero_caracteres",
                          1: "primeiras_letras",
                          2: "letras_a",
                          3: "presenca_hu"})
df_exerc7

                numero_caracteres primeiras_letras letras_a presenca_hu
interleucina_6                 14               in        1       False
interferon_gama                15               in        2       False
TNF-alpha                       9               TN        2       False
interleucina_12                15               in        1       False
TGF-beta                        8               TG        1       False

In [14]:
df_exerc7.to_csv('df_exerc7.csv')

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [18]:
df_exerc7[['numero_caracteres', 'letras_a']]

                numero_caracteres letras_a
interleucina_6                 14        1
interferon_gama                15        2
TNF-alpha                       9        2
interleucina_12                15        1
TGF-beta                        8        1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [21]:
df_exerc7.loc[df_exerc7.index[[0,2]],
              'presenca_hu']

interleucina_6    False
TNF-alpha         False
Name: presenca_hu, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [22]:
import os

Caching the list of root modules, please wait!
(This will only be done once - type '%rehashx' to reset cache!)

In [30]:
os.listdir()

['02 - introdução.ipynb',
 '04 - objetos_simples.ipynb',
 '05-Objetos_Compostos_1.ipynb',
 '06-Objetos_Compostos_2.ipynb',
 'img']

In [31]:
df_ex10 = pd.read_csv('C:/Users/Livia/.vscode/aulas_python_doutorado/dados/data.csv')

In [32]:
df_ex10.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [37]:
entradas = len(df_ex10)

In [38]:
tipos_colunas = df_ex10.dtypes.tolist()

In [39]:
contagem_tipos = df_ex10.dtypes.value_counts().tolist()

In [36]:
lista_1 = df_ex10.iloc[:, 0]
lista_2 = df_ex10.iloc[:, 3]
lista_3 = df_ex10.iloc[:, 8]

print(lista_1)
print(lista_2)
print(lista_3)

0        119736
1        448094
2        206893
3        333743
4        172534
          ...
36629    404309
36630    465875
36631    791209
36632    322627
36633    398149
Name: policyID, Length: 36634, dtype: int64
0         498960.0
1        1322376.3
2         190724.4
3              0.0
4              0.0
           ...
36629          0.0
36630    1297057.5
36631     173286.9
36632    1499781.6
36633     373488.3
Name: eq_site_limit, Length: 36634, dtype: float64
0         792148.90
1        1438163.57
2         192476.78
3          86854.48
4         246144.49
            ...
36629     155065.65
36630    1577500.79
36631     205527.97
36632    1768782.43
36633     596003.67
Name: tiv_2012, Length: 36634, dtype: float64

In [42]:
medias = [lista_1.mean(),
          lista_2.mean(),
          lista_3.mean()]

medias

[np.float64(548661.9371894961),
 np.float64(731478.0068460993),
 np.float64(2571004.0973420865)]

In [43]:
desvios = [lista_1.std(),
           lista_2.std(),
           lista_3.std()]

desvios

[np.float64(259912.9264939009),
 np.float64(17523003.588415086),
 np.float64(20367766.569178067)]

In [44]:
terceiro_quartil = [lista_1.quantile(0.75),
                    lista_2.quantile(0.75),
                    lista_3.quantile(0.75)]

terceiro_quartil

[np.float64(774252.0), np.float64(0.0), np.float64(1128871.1824999999)]

In [47]:
dict_ex10_lista6 = {
    "numero de entradas": entradas,
    "tipos de colunas": tipos_colunas,
    "contagem dos tipos": contagem_tipos,
    "medias": medias,
    "desvios": desvios,
    "terceiro quartil": terceiro_quartil
}

dict_ex10_lista6

{'numero de entradas': 36634,
 'tipos de colunas': [dtype('int64'),
  dtype('O'),
  dtype('O'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  dtype('O'),
  dtype('O'),
  dtype('int64')],
 'contagem dos tipos': [11, 4, 3],
 'medias': [np.float64(548661.9371894961),
  np.float64(731478.0068460993),
  np.float64(2571004.0973420865)],
 'desvios': [np.float64(259912.9264939009),
  np.float64(17523003.588415086),
  np.float64(20367766.569178067)],
 'terceiro quartil': [np.float64(774252.0),
  np.float64(0.0),
  np.float64(1128871.1824999999)]}