# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [7]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

p and q and r and s and t

False

In [8]:
not (p and q and r and s and t)

True

In [9]:
p or q or r or s or t

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [10]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [11]:
p or q or r or s or t or u

True

In [12]:
not (p or q or r or s or t or u)

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [1]:
import pandas as pd

In [2]:
df_ex3 = pd.read_csv('df_ex7.csv', index_col='Unnamed: 0').round(3)
df_ex3

         Coluna 1  Coluna 2  Coluna 3  Coluna 4  Médias
Linha 1     2.600     2.800    34.729     0.069  10.050
Linha 2     0.139     1.612     1.673     5.893   2.329
Linha 3     0.263     0.372     2.600     2.800   1.509
Linha 4    34.729     0.069     0.139     1.612   9.137
Linha 5     1.673     5.893     0.263     0.372   2.050
Médias      7.881     2.149     7.881     2.149   5.015

In [5]:
((df_ex3.loc['Linha 2'] == df_ex3.loc['Linha 3']).all()) or ((df_ex3.loc['Linha 3'] == df_ex3.loc['Linha 4']).all())

np.False_

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [13]:
(df_ex3.loc['Linha 1'] >= 10).all()

np.False_

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [14]:
((df_ex3['Coluna 3'] >= 0) & (df_ex3['Coluna 3'] <= 40)).all()

np.True_

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [15]:
(df_ex3.loc['Médias'] > 10).any()

np.False_

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [16]:
df_ex3[(df_ex3 > 5) & (df_ex3 < 7)]

         Coluna 1  Coluna 2  Coluna 3  Coluna 4  Médias
Linha 1       NaN       NaN       NaN       NaN     NaN
Linha 2       NaN       NaN       NaN     5.893     NaN
Linha 3       NaN       NaN       NaN       NaN     NaN
Linha 4       NaN       NaN       NaN       NaN     NaN
Linha 5       NaN     5.893       NaN       NaN     NaN
Médias        NaN       NaN       NaN       NaN   5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [17]:
df_ex3[(df_ex3 <= 5) | (df_ex3 >= 7)]

         Coluna 1  Coluna 2  Coluna 3  Coluna 4  Médias
Linha 1     2.600     2.800    34.729     0.069  10.050
Linha 2     0.139     1.612     1.673       NaN   2.329
Linha 3     0.263     0.372     2.600     2.800   1.509
Linha 4    34.729     0.069     0.139     1.612   9.137
Linha 5     1.673       NaN     0.263     0.372   2.050
Médias      7.881     2.149     7.881     2.149     NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [19]:
array_1 = df_ex3['Coluna 4'].to_numpy()
array_2 = df_ex3['Médias'].to_numpy()

print(array_1)
print(array_2)

[0.069 5.893 2.8   1.612 0.372 2.149]
[10.05   2.329  1.509  9.137  2.05   5.015]

In [20]:
((array_1 >= 2) & (array_2 <= 5)).any()

np.True_

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [21]:
((array_1 > -1) & (array_1 < 12)).all() and ((array_2 > -1) & (array_2 <12)).all()

np.True_